export const financeResources = [
  {
    id: "khan-financial-literacy",
    title: "Financial Literacy",
    provider: "Khan Academy",
    category: "Foundations",
    type: "Course",
    level: "Beginner",
    access: "No cost",
    description: "Short lessons on budgeting, credit, taxes, insurance, investing, and paying for college.",
    url: "https://www.khanacademy.org/college-careers-more/financial-literacy",
    featured: true,
  },
  {
    id: "investor-students",
    title: "Saving and Investing for Students",
    provider: "U.S. SEC",
    category: "Foundations",
    type: "Guide",
    level: "Beginner",
    access: "No account",
    description: "A student-first introduction to compounding, diversification, risk, fraud, and investing plans.",
    url: "https://www.investor.gov/additional-resources/general-resources/publications-research/publications/saving-investing-students",
    featured: true,
  },
  {
    id: "mit-finance-theory",
    title: "Finance Theory I",
    provider: "MIT OpenCourseWare",
    category: "Foundations",
    type: "Course",
    level: "Intermediate",
    access: "No account",
    description: "University-level lectures, problem sets, and exams covering present value, risk, and asset pricing.",
    url: "https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/",
    featured: true,
  },
  {
    id: "yale-financial-markets",
    title: "Financial Markets",
    provider: "Open Yale Courses",
    category: "Foundations",
    type: "Course",
    level: "Intermediate",
    access: "No account",
    description: "Robert Shiller's complete Yale course on markets, institutions, behavioral finance, and risk.",
    url: "https://oyc.yale.edu/economics/econ-252",
  },
  {
    id: "openstax-economics",
    title: "Principles of Economics",
    provider: "OpenStax",
    category: "Economics",
    type: "Textbook",
    level: "Beginner",
    access: "No account",
    description: "A complete, peer-reviewed economics textbook available online and as a downloadable PDF.",
    url: "https://openstax.org/details/books/principles-economics-3e",
  },
  {
    id: "mit-microeconomics",
    title: "Principles of Microeconomics",
    provider: "MIT OpenCourseWare",
    category: "Economics",
    type: "Course",
    level: "Intermediate",
    access: "No account",
    description: "Full undergraduate course materials on consumer behavior, firms, markets, and public policy.",
    url: "https://ocw.mit.edu/courses/14-01-principles-of-microeconomics-fall-2023/",
  },
  {
    id: "fed-education",
    title: "Federal Reserve Education",
    provider: "Federal Reserve System",
    category: "Economics",
    type: "Learning hub",
    level: "All levels",
    access: "No account",
    description: "Lessons, videos, and activities explaining money, banking, inflation, and the U.S. economy.",
    url: "https://www.federalreserveeducation.org/",
  },
  {
    id: "ny-fed-high-school",
    title: "High School Learning Resources",
    provider: "Federal Reserve Bank of New York",
    category: "Economics",
    type: "Learning hub",
    level: "Beginner",
    access: "No account",
    description: "Economics and personal-finance materials built specifically for high-school classrooms.",
    url: "https://www.newyorkfed.org/outreach-and-education/high-school",
  },
  {
    id: "accounting-coach",
    title: "Accounting Basics",
    provider: "AccountingCoach",
    category: "Accounting",
    type: "Course",
    level: "Beginner",
    access: "Free lessons",
    description: "Clear explanations of financial statements, debits and credits, ratios, and bookkeeping.",
    url: "https://www.accountingcoach.com/accounting-basics/explanation",
  },
  {
    id: "sec-beginner-statements",
    title: "Beginners' Guide to Financial Statements",
    provider: "U.S. SEC",
    category: "Accounting",
    type: "Guide",
    level: "Beginner",
    access: "No account",
    description: "A concise guide to income statements, balance sheets, cash flow, and shareholder equity.",
    url: "https://www.sec.gov/about/reports-publications/investor-publications/beginners-guide-financial-statements",
  },
  {
    id: "damodaran-valuation",
    title: "Valuation Course and Materials",
    provider: "NYU Stern, Aswath Damodaran",
    category: "Valuation",
    type: "Course",
    level: "Advanced",
    access: "No account",
    description: "Lectures, notes, cases, and tools from one of the most respected valuation professors.",
    url: "https://pages.stern.nyu.edu/~adamodar/New_Home_Page/valuation/val.htm",
  },
  {
    id: "damodaran-spreadsheets",
    title: "Valuation Spreadsheets",
    provider: "NYU Stern, Aswath Damodaran",
    category: "Valuation",
    type: "Templates",
    level: "Advanced",
    access: "Direct download",
    description: "Downloadable DCF, dividend, cost-of-capital, multiples, and acquisition models.",
    url: "https://pages.stern.nyu.edu/~adamodar/New_Home_Page/eqspread.htm",
  },
  {
    id: "damodaran-data",
    title: "Corporate Finance and Valuation Data",
    provider: "NYU Stern, Aswath Damodaran",
    category: "Valuation",
    type: "Dataset",
    level: "Intermediate",
    access: "Direct download",
    description: "Current and archived industry data for margins, multiples, betas, risk premiums, and returns.",
    url: "https://pages.stern.nyu.edu/~adamodar/New_Home_Page/data.html",
  },
  {
    id: "cfi-resources",
    title: "Corporate Finance Resources",
    provider: "Corporate Finance Institute",
    category: "Valuation",
    type: "Reference",
    level: "All levels",
    access: "Free articles",
    description: "A broad reference library for accounting, valuation, capital markets, and financial modeling.",
    url: "https://corporatefinanceinstitute.com/resources/",
  },
  {
    id: "wall-street-prep-knowledge",
    title: "Finance Knowledge Base",
    provider: "Wall Street Prep",
    category: "Valuation",
    type: "Reference",
    level: "Intermediate",
    access: "Free articles",
    description: "Technical explainers on investment banking, modeling, private equity, and corporate finance.",
    url: "https://www.wallstreetprep.com/knowledge/",
  },
  {
    id: "sec-edgar",
    title: "EDGAR Company Filings",
    provider: "U.S. SEC",
    category: "Research & Data",
    type: "Database",
    level: "All levels",
    access: "No account",
    description: "Search public-company 10-Ks, 10-Qs, 8-Ks, proxy statements, and ownership disclosures.",
    url: "https://www.sec.gov/search-filings",
  },
  {
    id: "fred",
    title: "FRED Economic Data",
    provider: "Federal Reserve Bank of St. Louis",
    category: "Research & Data",
    type: "Database",
    level: "All levels",
    access: "No account",
    description: "Graph and download hundreds of thousands of economic time series from trusted sources.",
    url: "https://fred.stlouisfed.org/",
  },
  {
    id: "bls-data",
    title: "Labor Statistics Data",
    provider: "U.S. Bureau of Labor Statistics",
    category: "Research & Data",
    type: "Database",
    level: "Intermediate",
    access: "No account",
    description: "Official inflation, employment, wages, productivity, and occupational data.",
    url: "https://www.bls.gov/data/",
  },
  {
    id: "bea-data",
    title: "U.S. Economic Accounts",
    provider: "Bureau of Economic Analysis",
    category: "Research & Data",
    type: "Database",
    level: "Intermediate",
    access: "No account",
    description: "Official GDP, income, trade, industry, and regional economic datasets.",
    url: "https://www.bea.gov/data",
  },
  {
    id: "world-bank-data",
    title: "World Bank Open Data",
    provider: "World Bank",
    category: "Research & Data",
    type: "Database",
    level: "All levels",
    access: "No account",
    description: "Global development indicators covering growth, trade, poverty, education, and finance.",
    url: "https://data.worldbank.org/",
  },
  {
    id: "ny-fed-data",
    title: "Markets Data Dashboard",
    provider: "Federal Reserve Bank of New York",
    category: "Research & Data",
    type: "Database",
    level: "Advanced",
    access: "No account",
    description: "Primary-source data for rates, reserves, repo markets, foreign exchange, and Fed operations.",
    url: "https://www.newyorkfed.org/markets/data-hub",
  },
  {
    id: "excel-training",
    title: "Excel Training",
    provider: "Microsoft",
    category: "Tools & Modeling",
    type: "Tutorials",
    level: "Beginner",
    access: "No cost",
    description: "Official lessons on formulas, charts, PivotTables, formatting, and data analysis.",
    url: "https://support.microsoft.com/en-us/excel",
  },
  {
    id: "macabacus-shortcuts",
    title: "Excel Keyboard Shortcuts",
    provider: "Macabacus",
    category: "Tools & Modeling",
    type: "Reference",
    level: "Intermediate",
    access: "No account",
    description: "A practical shortcut reference for faster spreadsheet navigation and modeling.",
    url: "https://macabacus.com/learn/excel/keyboard-shortcuts",
  },
  {
    id: "google-sheets-training",
    title: "Google Sheets Training",
    provider: "Google Workspace Learning Center",
    category: "Tools & Modeling",
    type: "Tutorials",
    level: "Beginner",
    access: "No cost",
    description: "Quick-start guides for formulas, analysis, collaboration, charts, and data cleanup.",
    url: "https://support.google.com/a/users/answer/9282959?hl=en-419",
  },
  {
    id: "tradingview",
    title: "Market Charts and Screeners",
    provider: "TradingView",
    category: "Tools & Modeling",
    type: "Tool",
    level: "All levels",
    access: "Free plan",
    description: "Interactive charts, screeners, watchlists, and market data for practicing technical research.",
    url: "https://www.tradingview.com/",
  },
  {
    id: "portfolio-visualizer",
    title: "Portfolio Visualizer",
    provider: "Portfolio Visualizer",
    category: "Tools & Modeling",
    type: "Tool",
    level: "Intermediate",
    access: "Free tools",
    description: "Backtest portfolios, compare allocations, and explore factor and asset-class behavior.",
    url: "https://www.portfoliovisualizer.com/",
  },
  {
    id: "forage-finance",
    title: "Finance Job Simulations",
    provider: "Forage",
    category: "Careers",
    type: "Experience",
    level: "All levels",
    access: "Free account",
    description: "Self-paced virtual projects based on tasks from investment banks, asset managers, and firms.",
    url: "https://www.theforage.com/job-simulations?careers=finance",
  },
  {
    id: "harvard-resume",
    title: "Guide to Creating a Strong Résumé",
    provider: "Harvard Career Services",
    category: "Careers",
    type: "Guide",
    level: "All levels",
    access: "No account",
    description: "Examples and guidance for writing clear, results-focused résumés and cover letters.",
    url: "https://careerservices.fas.harvard.edu/resources/create-a-strong-resume/",
  },
  {
    id: "bls-career-outlook",
    title: "Business and Financial Careers",
    provider: "Occupational Outlook Handbook",
    category: "Careers",
    type: "Career guide",
    level: "Beginner",
    access: "No account",
    description: "Compare role descriptions, education, compensation, and job outlook using official data.",
    url: "https://www.bls.gov/ooh/business-and-financial/home.htm",
  },
  {
    id: "finra-careers-finance",
    title: "Investing Basics",
    provider: "FINRA",
    category: "Markets & Investing",
    type: "Learning hub",
    level: "Beginner",
    access: "No account",
    description: "Independent primers on stocks, bonds, funds, fees, risk, and account types.",
    url: "https://www.finra.org/investors/investing/investing-basics",
  },
  {
    id: "cboe-options",
    title: "Options Institute Learning Center",
    provider: "Cboe",
    category: "Markets & Investing",
    type: "Course",
    level: "Intermediate",
    access: "Free account",
    description: "Structured courses and explainers on options, derivatives, volatility, and market mechanics.",
    url: "https://www.cboe.com/optionsinstitute/",
  },
  {
    id: "morning-brew",
    title: "Morning Brew",
    provider: "Morning Brew",
    category: "News & Context",
    type: "Newsletter",
    level: "Beginner",
    access: "Free email",
    description: "A concise daily briefing on business, markets, technology, and the economy.",
    url: "https://www.morningbrew.com/daily",
  },
  {
    id: "reuters-markets",
    title: "Markets Coverage",
    provider: "Reuters",
    category: "News & Context",
    type: "News",
    level: "All levels",
    access: "Free access",
    description: "Global reporting on equities, rates, currencies, commodities, deals, and economic policy.",
    url: "https://www.reuters.com/markets/",
  },
  {
    id: "liberty-street-economics",
    title: "Liberty Street Economics",
    provider: "Federal Reserve Bank of New York",
    category: "News & Context",
    type: "Research blog",
    level: "Advanced",
    access: "No account",
    description: "Readable analysis from New York Fed economists on banking, markets, labor, and policy.",
    url: "https://libertystreeteconomics.newyorkfed.org/",
  },
  {
    id: "kaggle-pandas",
    title: "Pandas",
    provider: "Kaggle Learn",
    category: "Quant & Coding",
    type: "Course",
    level: "Beginner",
    access: "Free account",
    description: "A short, hands-on introduction to analyzing tabular financial and economic data with Python.",
    url: "https://www.kaggle.com/learn/pandas",
  },
  {
    id: "python-for-everybody",
    title: "Python for Everybody",
    provider: "University of Michigan",
    category: "Quant & Coding",
    type: "Course",
    level: "Beginner",
    access: "No account",
    description: "Free lessons, book chapters, assignments, and videos for learning Python from scratch.",
    url: "https://www.py4e.com/",
  },
  {
    id: "pandas-getting-started",
    title: "Pandas Getting Started",
    provider: "pandas",
    category: "Quant & Coding",
    type: "Documentation",
    level: "Intermediate",
    access: "No account",
    description: "Official tutorials for importing, cleaning, reshaping, calculating, and plotting data.",
    url: "https://pandas.pydata.org/docs/getting_started/index.html",
  },
  {
    id: "google-colab",
    title: "Colab Notebooks",
    provider: "Google",
    category: "Quant & Coding",
    type: "Tool",
    level: "All levels",
    access: "Free account",
    description: "Run Python notebooks in the browser without installing software or configuring a computer.",
    url: "https://colab.research.google.com/",
  },
  {
    id: "wharton-investment-competition",
    title: "Global High School Investment Competition",
    provider: "Wharton Global Youth",
    category: "Competitions",
    type: "Competition",
    level: "Intermediate",
    access: "Free entry",
    description: "Teams build and defend a long-term investment strategy for a real-world client case.",
    url: "https://globalyouth.wharton.upenn.edu/investment-competition/",
  },
  {
    id: "diamond-challenge",
    title: "Diamond Challenge",
    provider: "University of Delaware",
    category: "Competitions",
    type: "Competition",
    level: "All levels",
    access: "Free entry",
    description: "Build and pitch a business or social-innovation concept with a high-school team.",
    url: "https://diamondchallenge.org/",
  },
  {
    id: "fdic-money-smart",
    title: "Money Smart for Young People",
    provider: "FDIC",
    category: "Personal Finance",
    type: "Learning hub",
    level: "Beginner",
    access: "No account",
    description: "Age-based lessons on earning, spending, banking, credit, saving, and financial decisions.",
    url: "https://www.fdic.gov/consumer-resource-center/money-smart-young-people",
  },
  {
    id: "cfpb-high-school-finance",
    title: "High School Financial Activities",
    provider: "Consumer Financial Protection Bureau",
    category: "Personal Finance",
    type: "Course",
    level: "Beginner",
    access: "No account",
    description: "Hands-on high-school activities covering budgeting, credit, saving, investing, and paying for college.",
    url: "https://www.consumerfinance.gov/consumer-tools/educator-tools/youth-financial-education/teach/activities/?grade_level=1&grade_level=2",
  },
];

export const resourceCategories = [
  "All resources",
  ...new Set(financeResources.map((resource) => resource.category)),
];
